from __future__ import annotations

from config import _iso

CARE_PROFILES = [
    {
        'common_name': 'Banana Plant',
        'category': 'fruiting tropical',
        'indoor_suitability': 0,
        'beginner_friendly': 0,
        'light_profile': 'full sun',
        'ideal_ph_min': 5.5,
        'ideal_ph_max': 7.0,
        'watering_note': 'Keep evenly moist and feed more often in warm weather.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Heavy feeder and fast grower.',
    },
    {
        'common_name': 'Cherry Tomatoes',
        'category': 'vegetable',
        'indoor_suitability': 0,
        'beginner_friendly': 1,
        'light_profile': 'full sun',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 6.8,
        'watering_note': 'Water deeply and keep foliage dry.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Best with steady moisture and airflow.',
    },
    {
        'common_name': 'Hibiscus',
        'category': 'flowering shrub',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'bright light',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 6.8,
        'watering_note': 'Likes regular water but not soggy soil.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Sensitive to heat spikes and dry wind.',
    },
    {
        'common_name': 'Succulents',
        'category': 'desert plants',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'bright light',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 7.5,
        'watering_note': 'Water only after the mix dries out fully.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Avoid watering in the hottest part of the day.',
    },
    {
        'common_name': 'Basil',
        'category': 'herb',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'bright indirect light',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 7.0,
        'watering_note': 'Keep soil evenly moist and pinch often.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Sensitive to heat and inconsistent watering.',
    },
    {
        'common_name': 'Mint',
        'category': 'herb',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'partial shade',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 7.0,
        'watering_note': 'Keep consistently damp, especially in containers.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Fast grower and easy to manage in a pot.',
    },
    {
        'common_name': 'Monstera',
        'category': 'houseplant',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'low to bright indirect light',
        'ideal_ph_min': 5.8,
        'ideal_ph_max': 6.5,
        'watering_note': 'Water when the top inch dries out.',
        'best_watering_time_hot_weather': 'morning',
        'notes': 'Repot when roots circle the pot.',
    },
    {
        'common_name': 'Snake Plant',
        'category': 'houseplant',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'low light tolerant',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 7.5,
        'watering_note': 'Allow the mix to dry almost fully between waterings.',
        'best_watering_time_hot_weather': 'morning',
        'notes': 'One of the easiest low-light plants.',
    },
    {
        'common_name': 'Rose',
        'category': 'flowering shrub',
        'indoor_suitability': 0,
        'beginner_friendly': 0,
        'light_profile': 'full sun',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 6.8,
        'watering_note': 'Deep watering once or twice a week is usually better than frequent shallow watering.',
        'best_watering_time_hot_weather': 'early morning',
        'notes': 'Prune after flowering and keep airflow open.',
    },
    {
        'common_name': 'ZZ Plant',
        'category': 'houseplant',
        'indoor_suitability': 1,
        'beginner_friendly': 1,
        'light_profile': 'low light tolerant',
        'ideal_ph_min': 6.0,
        'ideal_ph_max': 7.5,
        'watering_note': 'Water sparingly and avoid wet feet.',
        'best_watering_time_hot_weather': 'morning',
        'notes': 'Great beginner plant for low light.',
    },
]

PERSONAL_PLANTS = [
    {
        'name': 'Banana Plant',
        'species': 'Musa acuminata',
        'nickname': 'Tropicana',
        'location': 'Back Patio',
        'plant_type': 'outdoor',
        'status': 'active',
        'purchase_date': '2025-02-14',
        'watering_interval_days': 2,
        'last_watered': _iso(2),
        'last_fertilized': _iso(16),
        'last_repot': _iso(140),
        'sunlight_hours': 8.0,
        'optimal_ph_min': 5.5,
        'optimal_ph_max': 7.0,
        'notes': 'Heavy feeder and strong grower in warm weather.',
    },
    {
        'name': 'Tomato Plant',
        'species': 'Solanum lycopersicum',
        'nickname': 'Brandy',
        'location': 'Raised Bed',
        'plant_type': 'outdoor',
        'status': 'monitor',
        'purchase_date': '2025-03-10',
        'watering_interval_days': 2,
        'last_watered': _iso(1),
        'last_fertilized': _iso(12),
        'last_repot': _iso(0),
        'sunlight_hours': 8.5,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 6.8,
        'notes': 'Yellowing leaves and brown spotting need monitoring.',
    },
    {
        'name': 'Hibiscus',
        'species': 'Hibiscus rosa-sinensis',
        'nickname': 'Ruby',
        'location': 'Front Yard',
        'plant_type': 'outdoor',
        'status': 'active',
        'purchase_date': '2024-09-01',
        'watering_interval_days': 3,
        'last_watered': _iso(2),
        'last_fertilized': _iso(10),
        'last_repot': _iso(120),
        'sunlight_hours': 7.5,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 6.8,
        'notes': 'Heat sensitive in extreme afternoons.',
    },
    {
        'name': 'Monstera Deliciosa',
        'species': 'Monstera deliciosa',
        'nickname': 'Moss',
        'location': 'Living Room',
        'plant_type': 'indoor',
        'status': 'active',
        'purchase_date': '2024-05-11',
        'watering_interval_days': 7,
        'last_watered': _iso(6),
        'last_fertilized': _iso(20),
        'last_repot': _iso(64),
        'sunlight_hours': 5.5,
        'optimal_ph_min': 5.8,
        'optimal_ph_max': 6.5,
        'notes': 'Repotting history suggests it may be close to root bound.',
    },
    {
        'name': 'Sweet Basil',
        'species': 'Ocimum basilicum',
        'nickname': 'Pesto',
        'location': 'Kitchen Window',
        'plant_type': 'indoor',
        'status': 'sick',
        'purchase_date': '2025-04-12',
        'watering_interval_days': 2,
        'last_watered': _iso(3),
        'last_fertilized': _iso(18),
        'last_repot': _iso(45),
        'sunlight_hours': 6.5,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 7.0,
        'notes': 'Yellowing leaves and brown spots after recent heat.',
    },
    {
        'name': 'Mint',
        'species': 'Mentha spicata',
        'nickname': 'Sprig',
        'location': 'Herb Shelf',
        'plant_type': 'indoor',
        'status': 'active',
        'purchase_date': '2025-01-09',
        'watering_interval_days': 2,
        'last_watered': _iso(1),
        'last_fertilized': _iso(14),
        'last_repot': _iso(90),
        'sunlight_hours': 4.0,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 7.0,
        'notes': 'Fast growth, easy to compare against basil.',
    },
    {
        'name': 'Cucumber Vine',
        'species': 'Cucumis sativus',
        'nickname': 'Crunch',
        'location': 'Backyard Bed',
        'plant_type': 'outdoor',
        'status': 'monitor',
        'purchase_date': '2025-04-08',
        'watering_interval_days': 3,
        'last_watered': _iso(2),
        'last_fertilized': _iso(11),
        'last_repot': _iso(0),
        'sunlight_hours': 8.5,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 6.8,
        'notes': 'Humidity spikes caused mildew concern last season.',
    },
    {
        'name': 'Snake Plant',
        'species': 'Dracaena trifasciata',
        'nickname': 'Spear',
        'location': 'Office',
        'plant_type': 'indoor',
        'status': 'inactive',
        'purchase_date': '2024-11-16',
        'watering_interval_days': 21,
        'last_watered': _iso(18),
        'last_fertilized': _iso(60),
        'last_repot': _iso(250),
        'sunlight_hours': 2.0,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 7.5,
        'notes': 'Low-water plant, currently marked inactive.',
    },
    {
        'name': 'Succulent Mix',
        'species': 'Mixed succulents',
        'nickname': 'Desert Tray',
        'location': 'Sunny Shelf',
        'plant_type': 'indoor',
        'status': 'active',
        'purchase_date': '2024-08-19',
        'watering_interval_days': 14,
        'last_watered': _iso(10),
        'last_fertilized': _iso(40),
        'last_repot': _iso(180),
        'sunlight_hours': 6.0,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 7.5,
        'notes': 'Needs dry soil and morning watering during heat.',
    },
    {
        'name': 'Aloe Vera',
        'species': 'Aloe vera',
        'nickname': 'Gel',
        'location': 'Bedroom Shelf',
        'plant_type': 'indoor',
        'status': 'inactive',
        'purchase_date': '2024-07-20',
        'watering_interval_days': 21,
        'last_watered': _iso(22),
        'last_fertilized': _iso(70),
        'last_repot': _iso(300),
        'sunlight_hours': 5.0,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 7.0,
        'notes': 'Second inactive plant for demo queries.',
    },
    {
        'name': 'Rose',
        'species': 'Rosa spp.',
        'nickname': 'Velvet',
        'location': 'South Border',
        'plant_type': 'outdoor',
        'status': 'active',
        'purchase_date': '2024-03-14',
        'watering_interval_days': 4,
        'last_watered': _iso(2),
        'last_fertilized': _iso(15),
        'last_repot': _iso(150),
        'sunlight_hours': 7.0,
        'optimal_ph_min': 6.0,
        'optimal_ph_max': 6.8,
        'notes': 'Used for pruning tutorial and pest-control search.',
    },
]


def seed_data_loaded() -> bool:
    return True


__all__ = ['CARE_PROFILES', 'PERSONAL_PLANTS', 'seed_data_loaded']
